version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli@9.1.12
  build:
    commands:
        - echo Build started 
        - ng build --prod
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/frontend'
    discard-paths: yes