version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli@9.1.12
  build:
    commands:
        - echo Build started 
        - ng build --prod
  # post_build:
  #   commands:
  #       - aws s3 sync ./dist/frontend s3://angular-deploy-ui --delete
artifacts:
    files:
        - dist/*
        - appspec.yml
    discard-paths: no